#!/bin/bash
#       userdtn_adm == Start/Stop Daemon Processes for user_dtn
#
# Author:       David Miranda
# Date:         Monday Nov 14 2022
#
#
#######################################################################

USAGE="Usage: userdtn_adm {start | shutdown | stop}"

PATH=$PATH:`pwd`
export PATH

YES=0
NO=1

#set -x         # for debugging this script
# verify superuser status
uid=`id`
uid=`expr "$uid" : 'uid=\([0-9]*\)'`
if [ "${uid:=0}" -ne 0 ]
then
	echo "$0: Permission denied. You must be root or become superuser."
	exit 1
fi

if [ "$1" = start -a "$2" != NO ]; then
# put up message.
echo >&2
#echo >&2 "Checking where Im at.  "
fi

# Find the "OS", needed especially for AIX
VERSION=`uname -v`
OS="`uname -s|cut -d' ' -f1`"


RELEASE=`uname -r`  # release of OS

# userdtn_adm should have at least one and not more than 2 arguments
if [ $# -gt 2 -a $# -lt 1 ]
then
	echo ${USAGE}
	exit 1
fi

#if [ `uname -s` = Linux ]
#then
#	alias echo="echo -e"
#fi

#######################################################################
#
# Shell functions used within this script
#
#######################################################################

CONTIN="Press <ENTER> to continue: \c"

PS()
{
	ps -ef
	return 0
}

KillNamedProcess()
{
	PS | egrep " $1( |$)" | sed -e '/egrep/d' -e 's/^ *//' > ps.out
	cat ps.out | awk '{print $2}' > killpid
	
	if [ ! -s killpid ]
	then
		echo "Process $1 not running"
	else
		pid=`cat killpid`
		#send SIGINT since thats's what we are looking for
		echo "sending SIGINT to pid(s) ${pid} ($1)"
		kill -INT ${pid}
	fi
	rm killpid
	rm ps.out
}

CheckNamedProcess()
{
	PS | egrep " $1( |$)" | sed -e '/egrep/d' -e 's/^ *//' > ps.out
	cat ps.out | awk '{print $2}' > killpid
	
	if [ ! -s killpid ]
	then
		echo "Process $1 not running"
		rm killpid
		rm ps.out
		sleep 2
		echo
		echo "Tuning Module shutdown completed ..."
		sleep 2
		exit 0
	else
		rm killpid
		rm ps.out
	fi
}

#
# Get a yes or no answer from the user.  Argument 1 is prompt, 2 is default.
#
yorn()
{
        if [ "$2" = "" ] ; then
                prompt="$1? "
        else
                prompt="$1 [$2]? "
        fi

        while true ; do
                echo "$prompt\c"
                read input
                parsed=$input

                if [ "$parsed" = "" ] ; then
                        answer=$2
                else
                        answer=$input
                fi

                case $answer in
                        [yY]|[yY][eE]|[yY][eE][sS])
                                yorn_rsp=0
                                return 0 ; break ;;
                        [nN]|[nN][oO])
                                yorn_rsp=1
                                return 1 ; break ;;
                        *)
                                echo "Please answer yes or no."
                esac
        done
}

#
# get user input
#
termin()
{
    if [ "$2" = "" ] ; then
        prompt="$1? "
    else
        prompt="$1 [$2]? "
    fi

    echo "$prompt\c"
    read input
    answer=$input

    if [ "$answer" = "" ] ; then
        answer=$2
    fi
}

#
#
# MAIN
#
#
   trap 'exit 3' 15

    OS_TYP_VER=`uname -s`-`uname -r`

        #
        # Do system dependent things
        #
        case $OS_TYP_VER in
        Linux-*)
                OS_TYPE="OS_LINUX"
                USERDTNINST_DEF="/usr/tuningmod"
                ;;

        *)
                ;;
        esac

    if [ -f /usr/ucb/whoami ] ; then
       WHO="`/usr/ucb/whoami`"
    else
       if [ -f /usr/bin/whoami ] ; then
          WHO="`/usr/bin/whoami`"
       else
  WHO="`ps -f | grep ps | grep -v grep | awk '{print $1}'`"
       fi
    fi

    if [ "$WHO" != "root" ] ; then
        echo "Must be root to run this script, not $WHO"
        exit 1
    fi


#######################################################################
#
# Execution of script starts here.
#
#######################################################################
cd TM_PKG_DIR
nic=$(grep nic_to_use user_config.txt | awk '{print $2}')
attach_type=$(grep nic_attach_type user_config.txt | awk '{print $2}')

# examine the first parameter
case "$1" in
'start')        # Start the daemons


        # only one agent may be running on the system at a time
        PS > psef.out
        cat psef.out | egrep "user_dtn( |$)" | sed -e '/egrep/d' > ps.out
        if [ -s ps.out ]
        then
                echo "$0: error - user_dtn is already running:"
                cat ps.out
                exit 1
        fi

        rm psef.out ps.out

        echo
        echo "Tuning Module Startup ..."

        # Start the user_dtn
	sleep 1
	echo "Loading object and pinning map paths..."
	if [ "$attach_type" != "xdpoffload" ]
        then
                bpftool prog load int-sink2+filter.bpf.o /sys/fs/bpf/test pinmaps /sys/fs/bpf/test_maps/ 2>/tmp/tuningmodstart.out
        else
                bpftool prog load int-sink2+filter.bpf.o /sys/fs/bpf/test dev $nic pinmaps /sys/fs/bpf/test_maps/ 2>/tmp/tuningmodstart.out
        fi
	echo "Attaching bpf program to network interface using $attach_type..."
	bpftool net attach $attach_type pinned /sys/fs/bpf/test dev $nic
	sleep 1
	echo "Starting user_dtn process..."
        ./user_dtn $2

        sleep 1
        echo
        echo "Tuning Module Startup Completed"

        exit 0
        ;;


'stop' | 'shutdown')
        #       The stopcdm utility will complete only after
        #       executing the following shell commands.
        #       This ensures that all tuning module daemons have
        #       been killed.

        echo
        echo "TUNING MODULE SHUTDOWN ..."
        CheckNamedProcess ./user_dtn

        if [ $1 = 'shutdown' ]
        then
                        echo "    Do you still wish to stop the Tuning Module (y/n): "
                        read answer
                        case $answer in
                                 'y' | 'Y')
                                ;;
                        *)
                                exit 1
                        ;;
                        esac
        fi

        # kill the user_dtn daemon
        KillNamedProcess ./user_dtn
	sleep 1
	echo "Detaching bpf program from NIC..."
	bpftool net detach $attach_type dev $nic

	sleep 1
	echo "Removing bpf tuning module map directories no longer needed..."
	if [ -d /sys/fs/bpf/test_maps ]
	then
		rm -rf /sys/fs/bpf/test_maps
	fi
	
	sleep 1
	echo "Removing bpf tuning module files no longer needed..."
	if [ -f /sys/fs/bpf/test ]
	then
		rm -f /sys/fs/bpf/test
	fi

        sleep 2                 # for delay before possible re-start
        echo
        echo "TUNING MODULE SHUTDOWN COMPLETED ..."
        sleep 2                 # for delay before possible re-start
        exit 0
        ;;

*)
        echo ${USAGE}
        exit 1
        ;;
esac

exit 0

#
#####################################################################
# end of userdtn_adm
######################################################################

